# AUTOMATED TRANSACTION RISK MONITORING & ANALYTICS SYSTEM

In [35]:
import pandas as pd
import os

# ===============================================
# CONFIGURATION
# ===============================================
TRANSACTION_SOURCE_DIRECTORY = r'C:\Users\ARJUN\Downloads\files'
RISK_ENTITY_REFERENCE_PATH = r'C:\Users\ARJUN\Downloads\destination_folder\VPAs.xlsx'


# ===============================================
# TRANSACTION DATA INGESTION
# ===============================================
transaction_dataset_list = []

for source_file in os.listdir(TRANSACTION_SOURCE_DIRECTORY):
    if source_file.endswith('.csv'):
        
        # Build the output path (folder path + file name)
        source_file_path = os.path.join(TRANSACTION_SOURCE_DIRECTORY, source_file)
        
        # Read the files into a dataframe
        transaction_dataset = pd.read_csv(source_file_path)
        
        # Append the files
        transaction_dataset_list.append(transaction_dataset)
        
# Consolidate all transaction datasets
consolidated_dataframes = pd.concat(transaction_dataset_list, ignore_index = True)


# ===============================================
# MERCHANT PERFORMANCE ANALYSIS
# ===============================================
merchant_performance_summary = (
    consolidated_dataframes.groupby('MERCHANT')['AMOUNT']
    .agg(['count','sum'])
    .rename(
        columns = {'count':'Total_Transaction_Count',
                   'sum':'Total_Transaction_Value'})
    .sort_values(by = 'Total_Transaction_Value', ascending = False)
)

merchant_performance_summary['Average_Ticket_Size'] = (
    merchant_performance_summary['Total_Transaction_Value'] 
    / 
    merchant_performance_summary['Total_Transaction_Count']
)


# ===============================================
# TEMPORAL DATA PROCESSING
# ===============================================
consolidated_dataframes['COMPLETION-DATE'] = pd.to_datetime(consolidated_dataframes['COMPLETION-DATE'])
consolidated_dataframes['DATE'] = consolidated_dataframes['COMPLETION-DATE'].dt.date


# ===============================================
# CUSTOMER ACTIVITY ANALYSIS
# ===============================================
customer_activity_summary = (
    consolidated_dataframes.groupby('PAYERVA')
    .agg(Total_Transaction_Count = ('AMOUNT','count'), 
         Total_Transaction_Amount = ('AMOUNT','sum'), 
         Total_Active_Days = ('DATE','nunique'))
    .sort_values(by = 'Total_Active_Days', ascending = False)
)


# ===============================================
# HIGH RISK ENTITY MONITORING
# ===============================================
risk_reference_df = pd.read_excel(RISK_ENTITY_REFERENCE_PATH)

high_risk_entities = risk_reference_df['Payer VPA'].unique()

high_risk_entity_transactions = consolidated_dataframes[consolidated_dataframes['PAYERVA'].isin(high_risk_entities)]


# ===============================================
# REPORTING OUTPUT
# ===============================================
print('MERCHANT PERFORMANCE SUMMARY')
display(merchant_performance_summary.head(10))

print('CUSTOMER ACTIVITY SUMMARY')
display(customer_activity_summary.head(10))

print('HIGH-RISK ENTITY TRANSACTION ACTIVITY')
display(high_risk_entity_transactions.head(10))

MERCHANT PERFORMANCE SUMMARY

,Total_Transaction_Count,Total_Transaction_Value,Average_Ticket_Size
MERCHANT,,,
WRYNOVIA SOLUTIONS PRIVATE LIMITED,14183,25133936.99,1772.117111
SAVAX TECH AUTOMATION PRIVATE LIMITED,11351,25020137.56,2204.223201
FLEXSTREAM SOLUTIONS PVT LTD,132160,25013577.00,189.267380
purepelle creations private limited,140897,25013486.00,177.530295
HYPERDIGITALX PRIVATE LIMITED,9353,25011698.00,2674.189886
JYNARA LOGISTIC PRIVATE LIMITED,9122,24955416.00,2735.739531
NEOFORTE TECHPLAT PRIVATE LIMITED,72218,24903619.00,344.839500
APEX ARCADIA PRIVATE LIMITED,19418,24733058.00,1273.718097
HOLYNET SERVICES PRIVATE LIMITED,30448,24374858.00,800.540528
CUDBEAR HUB PRIVATE LIMITED,20163,24360871.00,1208.196747

CUSTOMER ACTIVITY SUMMARY

,Total_Transaction_Count,Total_Transaction_Amount,Total_Active_Days
PAYERVA,,,
vivek.2780-2@waaxis,37,27400.0,4
6301972847-3@axl,56,37600.0,4
saquibyusuf123@oksbi,17,26500.0,4
9414992119-6@axl,30,95500.0,4
9037121059-4@ibl,11,1300.0,3
8885949798@ybl,7,1080.0,3
9037115517@ptyes,5,1000.0,3
7849972390@ybl,26,3050.0,3
9792205592@ybl,11,1700.0,3
8141182631@ptyes,6,600.0,3

HIGH-RISK ENTITY TRANSACTION ACTIVITY

,TXNID,MERCHANT,BANK,REFID,AMOUNT,CHARGES,GST,SETTLEAMOUNT,INITATION-DATE,COMPLETION-DATE,QRTYPE,VPA,PAYER,PAYERVA,RRN,STATUS,DATE
3899,AXL17424d6726814c78a2c10745ff7c63a2,MERMAT ENTERPRISES PRIVATE LIMITED,JIO,PPTvJzTJMNsu4sfIGC,500.0,6.5,1.17,492.33,0,2025-10-11 00:12:00,Dynamic,mermatenterpris.8080@jiomerchant,MOHD K AHMAD,8285678082-4@axl,8.430000e+11,Success,2025-10-11
5950,AXLb30293fe5d1b4162aa74bb278d627649,MERMAT ENTERPRISES PRIVATE LIMITED,JIO,PPT8BqGBQfk3Mm2UxH,500.0,6.5,1.17,492.33,0,2025-10-11 00:17:00,Dynamic,mermatenterpris.8080@jiomerchant,MOHD K AHMAD,8285678082-4@axl,9.295872e+10,Success,2025-10-11
6434,YBL29d1ac933f574e9081bc2c41b9053e29,NUVOLA BELLA INFO SOLUTIONS PRIVATE LIMITED,JIO,RDP6910E20B019797,100.0,1.2,0.22,98.58,0,2025-10-11 00:19:00,Dynamic,nuvolabellainfo.8080@jiomerchant,CHIRANJEEVI R MISALA,m.chiranjeevi20@ybl,3.490000e+11,Success,2025-10-11
9212,IBL8b209fddbe8746ab961e4b0070503371,JYNARA LOGISTIC PRIVATE LIMITED,JIO,2.23E+18,500.0,6.0,1.08,492.92,0,2025-10-11 00:26:00,Dynamic,jynaralogisticp.8080@jiomerchant,KUMAR RITESH,kr.krritesh1234@ibl,1.590000e+11,Success,2025-10-11
10519,YBLeeb557afc51e459fb444369cd616f685,NEOFORTE TECHPLAT PRIVATE LIMITED,JIO,P1202511101538d186e,300.0,3.0,0.54,296.46,0,2025-10-11 00:30:00,Dynamic,neofortetechpla.8080@jiomerchant,CHIRANJEEVI R MISALA,m.chiranjeevi20@ybl,6.390000e+11,Success,2025-10-11
14905,AXL10b30c610c3a4bf592133e285e4e4d5b,HOLYNET SERVICES PRIVATE LIMITED,JIO,PPT0A8PDGIIj4jnbGD,500.0,3.5,0.63,495.87,0,2025-10-11 00:43:00,Dynamic,holynetservices.8080@jiomerchant,SK TOUSIF AHMED,sktousif284@axl,5.100000e+11,Success,2025-10-11
16769,AXLdf7d8c4e1fae43c2b037d4beb574d9ed,HOLYNET SERVICES PRIVATE LIMITED,JIO,PPTBHzzXE1v2BhI12m,500.0,3.5,0.63,495.87,0,2025-10-11 00:49:00,Dynamic,holynetservices.8080@jiomerchant,SK TOUSIF AHMED,sktousif284@axl,4.040000e+11,Success,2025-10-11
17074,AXLd798e9b0a7b54dafa5390488f5659d52,GRACEGLOW BEAUTY PRODUCTS PRIVATE LIMITED,JIO,P120251110032003815655,100.0,1.8,0.32,97.88,0,2025-10-11 00:50:00,Dynamic,graceglowbeauty.8080@jiomerchant,Noor Uddin,9535566871@axl,5.930000e+11,Success,2025-10-11
20576,AXL902f0214677842e59de28ab495abda71,NEOFORTE TECHPLAT PRIVATE LIMITED,JIO,P1202511105345ad475,200.0,2.0,0.36,197.64,0,2025-10-11 00:59:00,Dynamic,neofortetechpla.8080@jiomerchant,Nagamani Ramchander Battula,8668772108-2@axl,7.525222e+10,Success,2025-10-11
22775,YBL8f94cad7862244b193ec2550ade20576,MA STAR CONSULTANCY PRIVATE LIMITED,JIO,2.43E+18,5000.0,60.0,10.80,4929.20,0,2025-10-11 01:05:00,Dynamic,mastarconsultan.8080@jiomerchant,Mrs Jugni Khatun,7483885491-2@ybl,7.460000e+11,Success,2025-10-11